In [1]:

# Question 1
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/pycaret/pycaret/master/datasets/diamond.csv')
df.head()

   Carat Weight    Cut Color Clarity Polish Symmetry Report  Price
0          1.10  Ideal     H     SI1     VG       EX    GIA   5169
1          0.83  Ideal     H     VS1     ID       ID   AGSL   3470
2          0.85  Ideal     H     SI1     EX       EX    GIA   3183
3          0.91  Ideal     E     SI1     VG       VG    GIA   4370
4          0.83  Ideal     G     SI1     EX       EX    GIA   3171

In [3]:
#Question 2
df.groupby(['Cut', 'Color'])['Carat Weight'].mean()

Cut              Color
Fair             D        1.038333
                 E        1.000000
                 F        1.008333
                 G        1.143810
                 H        1.126250
                 I        1.053750
Good             D        1.165270
                 E        1.184818
                 F        1.207820
                 G        1.277973
                 H        1.362031
                 I        1.371478
Ideal            D        1.331571
                 E        1.258237
                 F        1.382948
                 G        1.401304
                 H        1.426092
                 I        1.419274
Signature-Ideal  D        1.302333
                 E        1.115714
                 F        1.200789
                 G        1.163906
                 H        1.217778
                 I        1.265366
Very Good        D        1.228226
                 E        1.243375
                 F        1.302791
                 G        1.376125
                 H        1.369788
                 I        1.410783
Name: Carat Weight, dtype: float64

In [4]:
#Question 3
df.groupby(['Clarity', 'Color']).size()

Clarity  Color
FL       D          4
IF       D         48
         E         18
         F         36
         G         70
         H         25
         I         22
SI1      D        276
         E        332
         F        341
         G        343
         H        409
         I        358
VS1      D         95
         E        116
         F        182
         G        358
         H        230
         I        211
VS2      D        137
         E        190
         F        270
         G        424
         H        271
         I        283
VVS1     D         24
         E         34
         F         60
         G         96
         H         44
         I         27
VVS2     D         77
         E         88
         F        124
         G        210
         H        100
         I         67
dtype: int64

In [5]:
#Question 4 (What is the average price depending on the cut and color?)
pivot_table = df.pivot_table(index='Cut', columns='Color', values='Price', aggfunc='mean')
pivot_table

Color,D,E,F,G,H,I
Cut,,,,,,
Fair,6058.250000,5370.625000,6063.625000,7345.523810,5908.500000,4573.187500
Good,10058.716216,8969.545455,9274.007519,9988.614865,9535.132812,8174.113043
Ideal,18461.953571,12647.107914,14729.426997,13570.310145,11527.700873,9459.588378
Signature-Ideal,19823.100000,11261.914286,13247.947368,10248.296875,9112.688889,8823.463415
Very Good,13218.826415,12101.910217,12413.905495,12354.013841,10056.106132,8930.031332


 The price is all about balancing the diamond's 4Cs . If you want like the "Ideal" cuts and "D" color grades, you'll pay a premium for that perfection. But if you're willing to compromise a bit on the brightness or accept a slight hint of color with a "Fair" cut or an "I" color grade, you can find options that are significantly more budget friendly.